### ISSUE TITLE
Truncated names should be longer (as a lot of empty space is present too)

### ISSUE THREAD

**Issue by GegznaV** [aeturrell/skimpy#373]
It seems that `skimpy` truncates variable names to 20 symbols. This seems to be unreasonable as there is a lot of empty space which is not used (indicated with yellow squares). This empty space can be removed to have more space for longer names

![image](https://user-images.githubusercontent.com/12725868/222814335-22db0f19-fc0f-4240-be5d-44bb9e1accc8.png)

![image](https://user-images.githubusercontent.com/12725868/222815688-e26c4a3c-1032-4f79-ae4c-099e03aba992.png)

1) How can we control the maximum length of variable names? 
2) Can this empty space be removed to longer names?
3) Can an ellipsis (single symbol "…") be used to pay attention to that variable name was truncated?
4) There should be a way to identify ambiguous variables after the names are truncated (see the second figure, red squares).

**Comment by GegznaV** [comment]
I see that this 20-character limit is hardcoded here:

https://github.com/aeturrell/skimpy/blob/4359c63ec6bc854a4e59302de0fa1d6f72aa2bd2/src/skimpy/__init__.py#L207

Can it be converted into a parameter/argument? Or can different lengths be used for different data types? Or can this vary depending on the available column width in order not to leave any empty space?

**Comment by aeturrell** [comment]
This could do with something that adjusts more naturally to the number of characters in the column. As a general rule, I try to avoid lots of parameter options in favour of good average settings as this makes the code more maintainable and more concise.

Will take a look at it and see if we can change the behaviour to better suit cases where the needed column space is less.

**Comment by aeturrell** [comment]
This can be closed as fixed in [98dbf76](https://github.com/aeturrell/skimpy/commit/98dbf762c76dfa951e023f30dac9224e11bf71b3). 

I've made a few changes:

- long column names now wrap
- instead of the strings of column names being truncated, as they were before, now the width of the columns is truncated

This means (in reference to your points):

1. You will have to do this yourself in your dataframe, but with the new column name wrapping, it should now be unambiguous as to which column you're dealing with when columns have similar characters for the first 20 characters
2. the empty space is removed
3. instead of ellipsis, we have a wrapped column
4. see 1.

Hopefully this helps improve the package for you and other users!
