### ISSUE TITLE
Wrong number of NA rows in the output?

### ISSUE THREAD

**Issue by aborruso** [aeturrell/skimpy#386]
Hi,
first of all thank you for this great tool.

If I run skimpy on [this 999 rows CSV](https://gist.github.com/e63b92eda1d65af6549c69b95b8b592e) I have 1000 NA rows.

Thank you

![image](https://user-images.githubusercontent.com/30607/224652316-3e5b550a-3254-4f34-b2fe-1c7787448abe.png)

**Comment by aeturrell** [comment]
Huh, that's strange! I will look into it. Before, I do, can I just check it's not the case that one row is being counted as the column header (ie there are 1000 rows in the csv file but one of those is being used as the column names so only 999 rows of data)?

**Comment by aeturrell** [comment]
This is occurring because `_round_dataframe` applies to all numeric columns, regardless of whether or not they are integers. This has some unfortunate consequences, such as rounding 988 to 990, 999 to 1000, and so on. As a solution, rounding should probably only be applied to specific columns that need it, ie it should be applied within the type-specific functions (eg `_string_variable_summary_table`) to *only* the relevant columns.

**Comment by aborruso** [comment]
I didn't remember this issue
Thak you very much @aeturrell
